# ---------------------- #
#      Site Configs      #
# ---------------------- #

name: Xummer
author: Xummer
production_url: xummer26.com
# pygments: true
permalink: /blog/:title.html
paginate: 10
paginate_path: /page/:num

# ---------------------- #
#         Jekyll         #
# ---------------------- #

safe: trua
markdown: redcarpet
exclude: ['Gemfile', 'Gemfile.lock']

redcarpet:
  extensions: ['no_intra_emphasis', 'fenced_code_blocks', 'tables']
  render_options:

# ---------------------- #
#      Compile Sass      #
# ---------------------- #

no_line_comments: true
sass_dir: _sass
fonts_dir: fonts
output_style: compressed

# ---------------------- #
#    Social Networks     #
# ---------------------- #

#duoshuo comments
duoshuo: xummer
simple_search: http://google.com/search
